### PR TITLE
Update to rocket v0.5.1

### PR DESCRIPTION
**Pull request by beyera**
Updated all dependencies and docs to [rocket v0.5.1](https://github.com/rwf2/Rocket/blob/v0.5.1/CHANGELOG.md#version-051-may-22-2024)

### CODE REVIEW

**Comment by beyera** [comment]
Pinging @ralpha on this one.

**Comment by michelbieleveld** [comment]
Pinging @ralpha as well ;-) would love to see to get the merged.

**Comment by necmettindev** [comment]
@ralpha @GREsau pinging :)

**Comment by SohumB** [comment]
This PR probably needs updates to 
```
rocket_db_pools 0.2.0
rocket_dyn_templates 0.2.0
rocket_ws 0.1.1
```

as indicated on rocket's changelog, right?

**Comment by jacks0n9** [comment]
please bro i can't even use okapi because it's set to `=0.5.0` for some reason. (i mean it is open source but still)

**Comment by ri-nat** [comment]
@ralpha @GREsau can some of you just merge this?

**Comment by ralpha** [comment]
Sorry for the late response.
Merged https://github.com/GREsau/okapi/pull/149 in favor of this one.
But made sure I have had all the changes from here too.

Please test if everything is working as intended with the current `master` branch and then I'll do a crates.io release soon (next days, after looking at other MR's and Issues.)

**Comment by ralpha** [comment]
Released [rocket-okapi version 0.9.0](https://crates.io/crates/rocket_okapi). So I hope you can all happily upgrade now. Have fun! And let me know if you find any issues.

**Comment by jacks0n9** [comment]
yayyy

**Pull request closed without merging**
