### PR TITLE
add support for request guards

### PR DESCRIPTION
**Pull request by TotalKrill**
This adds support for defining and getting request guards to define security schemes

result can look something like this: 

image

Will add an example for this soon

### CODE REVIEW

**Comment by TotalKrill** [comment]
So, glad to see you are back on this lib @GREsau 

Its a replacement for #44 and a continuation of #9

**Comment by svenstaro** [comment]
@ralpha I see you're maintaining this now, that's great! Any chance for a merge on this PR?

**Comment by TotalKrill** [comment]
This PR should be updated ideally, some people has left some patches for this on my forked version

this: https://github.com/TotalKrill/okapi/pull/3
this: https://github.com/TotalKrill/okapi/pull/1

**Comment by ralpha** [comment]
I'm currently working on integrating this into the current master. (so no need to change PR)
I'll also integrate https://github.com/TotalKrill/okapi/pull/3 and https://github.com/TotalKrill/okapi/pull/1.

@TotalKrill where there any other changes regarding this I need to take a look at?
And I see you have quite a few other changes in you `master` branch, does not look like there are any addition features added (is that correct?). But will also look over commits and see if there is anything that is needed.

And thanks for the PR :) This is a nice and needed feature to add.
P.S. if there is anything else you want to see in the next version, let me know, now it the time! (also for @svenstaro and anyone else)

**Comment by TotalKrill** [comment]
@ralpha Very happy to see this original project getting some well deserved attention again, nice work!

there are no real new features otherwise in my fork, I just really needed that security_scheme thingy, and was tired of depending on the github repo. 

I know user @mentaljam is working on some nice refactorings in a draft, https://github.com/TotalKrill/okapi/pull/4, but nothing to merge as of yet. 

Other than that there has not been any major changes, once this is in i will update my readme and publish a new version of my fork directing anyone who was using it back here again, as soon as these changes are pushed to crates.io that is. I know it takes a lot of effort maintaining this things, but if you feel like you are lagging behind, 

I do think its good to ask for help as soon as you feel that happening, there are a lot of good developers around, and publishing to crates.io semi-often means that users have an easy way to stick to a working version, if one of said developers do a bit to heavy breaking changes.  I do not want to maintain a branch, nor this library (no offense), but I will if i have to since I am using it :)

**Comment by ralpha** [comment]
This time I had the benefit that this update was needed for work, so I created it during my work. But I'll probably finish this PR after work so I can get it finished sooner.
I also look great care in making sure that the crate is prepared for future updates.
A lot of the changes also allow for things to be much easier to add/customized in the future.
See the full [changelog](https://github.com/GREsau/okapi/blob/master/rocket-okapi/CHANGELOG.md) for details, lot of nice things.

But updates will most likely come in bursts, like this time (at least from my side). But if I need help I'll ask!
Hope we can keep this crate maintained and reduce the fragmentation that happened because of inactivity.

**Comment by ralpha** [comment]
@TotalKrill In you code you have the `RequestHeaderInput::Parameter()` enum value. But I'm not sure about this.
It looks to my like this could never be used. If it takes a query or path parameter it would not be a Request Guard but a [Query String](https://rocket.rs/v0.5-rc/guide/requests/#query-strings).

So this could never be happen. Or am I wrong in assuming this? Could you please explain?

**Comment by TotalKrill** [comment]
Which code are you looking at, my branch or this PR?

**Comment by ralpha** [comment]
Okay made a bunch of changes and restructured a bunch of things. Also added support for al currently (Rocket 0.5.0-rc.1) items that currently implement `FromRequest`.

Also added examples for all the most common authentication methods so people can easily figure out how to do this. Also allowed me to test everything.
Hope you like it :D

**Pull request closed without merging**
