### PR TITLE
rocket 0.5-rc3

### PR DESCRIPTION
**Pull request by olback**

### CODE REVIEW

**Comment by IniterWorker** [comment]
Thank you for you contribution,
But, It is not enough. The crate `rocket_okapi_codegen` must be updated.
Please could you take care of the `rocket_okapi_codegen/Cargo.toml`.

**Comment by olback** [comment]
> But, It is not enough to be merged yet. The crate rocket_okapi_codegen must be updated.

Fixed. I also updated all the examples.

**Comment by briankung** [comment]
Hi! 👋 Is there anything preventing this from being merged? It's a blocker for us to update to rocket RC3 at work. Thanks!

**Comment by svenstaro** [comment]
@GREsau We've been running this in production without any problems. Could you merge this?

**Comment by ralpha** [comment]
PR looks good. Thanks for creating it. Sorry for the delay.
It is merged now. Will do a few more changed and hopefully get a new release out (soon) after that.

**Comment by briankung** [comment]
Thank you!

**Comment by ralpha** [comment]
New version has been published by now.
https://crates.io/crates/rocket_okapi/versions

**Pull request merged**
